SET SCHEMA LEARNING_TO_NOTE;

DROP TABLE TRAIN_RESULT;
CREATE COLUMN TABLE TRAIN_RESULT LIKE T_DDI_DATA;

DROP TABLE TRAIN_STAT;
CREATE COLUMN TABLE TRAIN_STAT LIKE T_R_STAT;

DROP PROCEDURE CALL_R;
CREATE PROCEDURE CALL_R()
LANGUAGE SQLSCRIPT AS
BEGIN
    train_data = SELECT * FROM TRAIN_DATA;
    CALL R_PREDICT(:train_data, T_DDI_DATA, T_R_STAT);
    INSERT INTO TRAIN_RESULT SELECT * FROM :T_DDI_DATA;
    INSERT INTO TRAIN_STAT SELECT * FROM :T_R_STAT;
END;
 
CALL CALL_R();
SELECT * FROM TRAIN_RESULT;
SELECT * FROM TRAIN_STAT;

