SET SCHEMA LEARNING_TO_NOTE;

DROP TABLE TRAIN_RESULT;
CREATE COLUMN TABLE TRAIN_RESULT LIKE T_TD_POS;

DROP TABLE TRAIN_STAT;
CREATE COLUMN TABLE TRAIN_STAT LIKE T_R_STAT;

DROP PROCEDURE CALL_R;
CREATE PROCEDURE CALL_R()
LANGUAGE SQLSCRIPT AS
BEGIN
    train_data = SELECT * FROM TD_POS_NOSTOP;
    CALL R_PREDICT_POS(:train_data, T_TD_POS, T_R_STAT);
    INSERT INTO TRAIN_RESULT SELECT * FROM :T_TD_POS;
    INSERT INTO TRAIN_STAT SELECT * FROM :T_R_STAT;
END;

CALL CALL_R();
SELECT * FROM TRAIN_RESULT;
SELECT * FROM TRAIN_STAT;

