CREATE TABLE COMMON_WORDS (ID INT, TOKEN VARCHAR(25));
INSERT INTO COMMON_WORDS VALUES(1, 'may');
INSERT INTO COMMON_WORDS VALUES(2, 'reduce');
INSERT INTO COMMON_WORDS VALUES(3, 'have');
INSERT INTO COMMON_WORDS VALUES(4, 'effect');
INSERT INTO COMMON_WORDS VALUES(5, 'increase');
INSERT INTO COMMON_WORDS VALUES(6, 'use');
