---OLD INDEX
-- SET SCHEMA "LEARNING_TO NOTE";
-- DROP FULLTEXT INDEX "FTI";
-- CREATE FULLTEXT INDEX "FTI" ON "DOCUMENTS" ("TEXT")
-- TEXT ANALYSIS ON
-- TEXT MINING OFF
-- CONFIGURATION 'LINGANALYSIS_FULL';

---SUPPOSEDLY NEW FTI-INDEX
CREATE FULLTEXT INDEX "FTI" on
"LEARNING_TO_NOTE"."DOCUMENTS"("TEXT")
LANGUAGE DETECTION ('EN')
ASYNC PHRASE INDEX RATIO 0.0
CONFIGURATION 'LINGANALYSIS_FULL'
SEARCH ONLY OFF
FAST PREPROCESS OFF
TEXT ANALYSIS ON
TOKEN SEPARATORS '\/;,.:-_()[]<>!?*@+{}="&#$~|';