SET SCHEMA LEARNING_TO_NOTE;

DROP PROCEDURE CALL_R;
DROP TYPE T_DDI_DATA;
DROP TABLE TRAIN_RESULT;

CREATE TYPE T_DDI_DATA AS TABLE (DDI TINYINT, "BEFORE" TEXT, BETWEEN TEXT, AFTER TEXT);

CREATE COLUMN TABLE TRAIN_RESULT LIKE T_DDI_DATA;


CREATE PROCEDURE CALL_R()
LANGUAGE SQLSCRIPT AS
BEGIN
    train_data = SELECT * FROM TRAIN_DATA;
    CALL R_TEST(:train_data, T_DDI_DATA);
    INSERT INTO TRAIN_RESULT SELECT * FROM :T_DDI_DATA;
END;

CALL CALL_R();
SELECT ddi, count(*) FROM TRAIN_RESULT group by ddi;
SELECT * FROM TRAIN_RESULT;
