SET SCHEMA LTN_TRAIN;

DROP TABLE TRAIN_RESULT;
CREATE COLUMN TABLE TRAIN_RESULT LIKE T_TRAIN_RESULTS;

DROP TABLE TRAIN_STAT;
CREATE COLUMN TABLE TRAIN_STAT LIKE T_R_STAT;

DROP PROCEDURE CALL_R_TRAIN;
CREATE PROCEDURE CALL_R_TRAIN()
LANGUAGE SQLSCRIPT AS
BEGIN
    train_data = SELECT * FROM TD_CLASSES;
    CALL R_TRAIN(:train_data, T_MODELS);
    INSERT INTO MODELS SELECT * FROM :T_MODELS;
END;


DROP PROCEDURE CALL_R_PREDICT;
CREATE PROCEDURE CALL_R_PREDICT()
LANGUAGE SQLSCRIPT AS
BEGIN
    data = SELECT E1_ID,E2_ID,"BEFORE",BETWEEN,AFTER,P_BEFORE,P_BETWEEN,P_AFTER FROM TD_CLASSES TABLESAMPLE SYSTEM (10);
    models = SELECT * FROM MODELS;
    CALL R_PREDICT(:data, :models, T_TRAIN_RESULTS, T_R_STAT);
    INSERT INTO TRAIN_RESULT SELECT * FROM :T_TRAIN_RESULTS;
    INSERT INTO TRAIN_STAT SELECT * FROM :T_R_STAT;
END;

CALL CALL_R_TRAIN();
SELECT * FROM MODELS;
CALL CALL_R_PREDICT();
SELECT * FROM TRAIN_RESULT;
SELECT * FROM TRAIN_STAT;
