SET SCHEMA LTN_TRAIN;

DROP TABLE TRAIN_RESULT;
CREATE COLUMN TABLE TRAIN_RESULT LIKE T_TRAIN_RESULTS;

DROP TABLE TRAIN_STAT;
CREATE COLUMN TABLE TRAIN_STAT LIKE T_R_STAT;

DROP PROCEDURE CALL_R_TRAIN_BINARY;
CREATE PROCEDURE CALL_R_TRAIN_BINARY()
LANGUAGE SQLSCRIPT AS
BEGIN
    DELETE FROM MODELS WHERE ID=1;
    train_data = SELECT * FROM TD_CLASSES;
    CALL R_TRAIN_BINARY(:train_data, T_MODELS);
    INSERT INTO MODELS SELECT * FROM :T_MODELS;
END;

DROP PROCEDURE CALL_R_TRAIN_CLASSES;
CREATE PROCEDURE CALL_R_TRAIN_CLASSES()
LANGUAGE SQLSCRIPT AS
BEGIN
    DELETE FROM MODELS WHERE ID=2;
    train_data = SELECT * FROM TD_CLASSES;
    model = SELECT * FROM MODELS WHERE ID=1;
    CALL R_TRAIN_CLASSES(:train_data, :model, T_MODELS);
    INSERT INTO MODELS SELECT * FROM :T_MODELS;
END;


DROP PROCEDURE CALL_R_PREDICT;
CREATE PROCEDURE CALL_R_PREDICT()
LANGUAGE SQLSCRIPT AS
BEGIN
    data = SELECT E1_ID,E2_ID,"BEFORE",BETWEEN,AFTER,P_BEFORE,P_BETWEEN,P_AFTER FROM TD_CLASSES_SAMPLED TABLESAMPLE SYSTEM (10);

    models = SELECT * FROM MODELS;
    CALL R_PREDICT(:data, :models, T_TRAIN_RESULTS, T_R_STAT);
    INSERT INTO TRAIN_RESULT SELECT * FROM :T_TRAIN_RESULTS;
    INSERT INTO TRAIN_STAT SELECT * FROM :T_R_STAT;
END;

CALL CALL_R_TRAIN_BINARY();
CALL CALL_R_TRAIN_CLASSES();
SELECT * FROM MODELS;
CALL CALL_R_PREDICT();
SELECT * FROM TRAIN_RESULT;
SELECT * FROM TRAIN_STAT;
